version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://book_catalog:book_catalog@db:5432/book_catalog
    depends_on:
      - db
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:14
    container_name: book-catalog-db
    environment:
      - POSTGRES_USER=book_catalog
      - POSTGRES_PASSWORD=book_catalog
      - POSTGRES_DB=book_catalog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: